load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hello",
    srcs = ["hello.c"],
)

sh_test(
    name = "test",
    size = "small",
    srcs = [
        "test.sh",
    ],
    args = [
        "$(location :hello)",
    ],
    data = [
        ":hello",
    ],
)
