load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:public"])

alias(
    name = "hello",
    actual = "@src//:hello",
)

sh_test(
    name = "test",
    size = "small",
    srcs = [
        "test.sh",
    ],
    args = [
        "$(location :hello)",
    ],
    data = [
        ":hello",
    ],
)
