load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "libhello",
    srcs = [
        "lib/basename-lgpl.c",
        "lib/c-ctype.c",
        "lib/c-strcasecmp.c",
        "lib/c-strncasecmp.c",
        "lib/cloexec.c",
        "lib/close-stream.c",
        "lib/closeout.c",
        "lib/dirname.c",
        "lib/basename.c",
        "lib/dirname-lgpl.c",
        "lib/stripslash.c",
        "lib/exitfail.c",
        "lib/fd-hook.c",
        "lib/getprogname.c",
        "lib/hard-locale.c",
        "lib/localcharset.c",
        "lib/malloca.c",
        "lib/mbchar.c",
        "lib/mbiter.c",
        "lib/mbslen.c",
        "lib/mbsstr.c",
        "lib/mbuiter.c",
        "lib/progname.c",
        "lib/propername.c",
        "lib/quotearg.c",
        "lib/setlocale_null.c",
        "lib/stat-time.c",
        "lib/striconv.c",
        "lib/strnlen1.c",
        "lib/trim.c",
        "lib/unistd.c",
        "lib/unistr/u8-mbtoucr.c",
        "lib/unistr/u8-uctomb.c",
        "lib/unistr/u8-uctomb-aux.c",
        "lib/uniwidth/width.c",
        "lib/version-etc.c",
        "lib/version-etc-fsf.c",
        "lib/wctype-h.c",
        "lib/xmalloc.c",
        "lib/xalloc-die.c",
        "lib/xstriconv.c",
        "lib/xstrndup.c",
        "lib/fcntl.c",
        "lib/mbrtowc.c",
    ],
    hdrs = glob([
        "lib/**/*.h",
        "lib/**/*.in.h",
    ]) + ["config.h"],
    strip_include_prefix = "",
    copts = [
        "-DLOCALEDIR=\\\"/usr/local/share/locale\\\"",
        "-DHAVE_CONFIG_H",
        "-Iexternal/+_repo_rules+src",
        "-Iexternal/+_repo_rules+src/lib",
        "-Wno-implicit-function-declaration",
        "-Wno-int-conversion",
    ],
)

cc_binary(
    name = "hello",
    srcs = [
        "src/hello.c",
        "src/system.h",
    ],
    deps = [":libhello"],
    copts = [
        "-DLOCALEDIR=\\\"/usr/local/share/locale\\\"",
        "-DHAVE_CONFIG_H",
        "-Iexternal/+_repo_rules+src",
        "-Iexternal/+_repo_rules+src/lib",
        "-Wno-implicit-function-declaration",
        "-Wno-int-conversion",
    ],
    visibility = ["//visibility:public"],
)
